### ISSUE TITLE
the dctls dont work in resolve on a windows pc

### ISSUE THREAD

**Issue by split-diopter** [mikaelsundell/dctl#1]
downloaded the dctls for the cineon inverse dctl to experiment with film scans, but the dctl doesn't work, i have the studio version of resolve 18.6 at the moment on a quite capable windows pc.

**Comment by mikaelsundell** [comment]
Did you copy the *.h headers not just the *.dctl scripts to DCTL?

**Comment by split-diopter** [comment]
Yes. I copied all the *.h as well as *.dctl files to the davinci luts folder

**Comment by mikaelsundell** [comment]
Send me an email on mikael.sundell@gmail.com and we figure it out 👍🏻

**Comment by mikaelsundell** [comment]
@split-diopter Should now be fixed and DCTLs confirmed to run on Davinci Resolve 18.6/ Windows.
