### ISSUE TITLE
Error in MS-Utils.h

### ISSUE THREAD

**Issue by 333csx** [mikaelsundell/dctl#2]
Line 137:

    return max(rgb, 0.0f);;

AFAIK you can't compare a float3 with a float.

use sth. like this :

__DEVICE__ float3 adjust_display(float3 rgb)
{
    rgb.x = _fmaxf(rgb.x, 0.0f);
    rgb.y = _fmaxf(rgb.y, 0.0f);
    rgb.z = _fmaxf(rgb.z, 0.0f);

    return rgb;;
}

**Comment by mikaelsundell** [comment]
Thanks for reporting, will push a new update on Monday including better support for non-mac platforms.

**Comment by mikaelsundell** [comment]
@333csx Should now be fixed and DCTLs confirmed to run on Davinci Resolve 18.6/ Windows.
