### ISSUE TITLE
Some DCTLs give me the error "DCTL compilation failed"

### ISSUE THREAD

**Issue by atriantas** [mikaelsundell/dctl#4]
Hi, I tried to use some DCTLs, but I am not successful in making them work (also am new in Davinci Resolve).
I am using the OFX DCTL at the node, the sliders appear but when I move them nothing is happening.
The DTCLs with the error are the "MS-Cineon-Expposure", "MS-CIneon-Invert", "MS-LogC3-Exposure", "MS-LogC3-Print".
Am I doing something wrong in my workflow?
My PC is pretty old, having Windows 10 with NVidia GTX660 with the latest driver update.
I download the scripts from the Releases section on GitHub and also as Raw.

At the log file I am getting this error:

[0x00000d44] | DVIP                 | ERROR | 2024-11-04 14:09:47,642 | DaVinci CTL compilation failed.
[0x00000d44] | DVIP                 | ERROR | 2024-11-04 14:09:47,642 | Failed to build program.
Build Status: -2
Build Options:  -w -DDEVICE_IS_OPENCL -DCOMPILER_IS_DVIP_RT -DKERNEL_TYPE_IS_DCTL -DVENDOR_IS_NVIDIA -cl-mad-enable -cl-fast-relaxed-math
Build Log: <kernel>:1937:14: error: must use 'struct' tag to refer to type 'CineonColor'
__CONSTANT__ CineonColor cineon_colors[] = {
             ^
             struct 
<kernel>:1967:18: error: expected ';' at end of declaration list
    float steps() {
                 ^
                 ;

[ResolveDebug.txt](https://github.com/user-attachments/files/17618214/ResolveDebug.txt)

**Comment by mikaelsundell** [comment]
Thanks for reporting this. First, did you copy all the necessary files—not just the individual .dctl scripts, but also the .h header files?

This is a common issue. I probably need to add an installer to make it easier.

Mikael

**Comment by atriantas** [comment]
First of all thank you for your quick reply and work. I am starting analog photography and I am searching for ways to handle my film negatives.

Yes, I copied all the files to the Davinci LUT folder. (Screenshot 1)
At first, I thought the problem was my workflow (screenshot 2), something like the color space of the timeline, but then I saw the "DaVinci CTL compilation failed" at log file.
Is it possible to have a problem with OpenGL on my PC?

![DCTL_Folder](https://github.com/user-attachments/assets/7035fbb8-a27c-4527-9340-b488a3225cd5)
![DCTL_Workflow](https://github.com/user-attachments/assets/accf58da-39cf-4a39-8fe0-ffc9a123e04a)

**Comment by mikaelsundell** [comment]
That's interesting. I'll double-check on my PC in a few hours and get back to you.

**Comment by atriantas** [comment]
Ok, I will test it also at my brother's PC (he doesn't have Davinci Resolve) to see if the computer is the problem.

**Comment by mikaelsundell** [comment]
I can confirm this is an Apple Metal vs CUDA DCTL issue. Apologies for not updating the DCTLs to work properly on Windows. It's late here, but I'll push a commit tomorrow. I need to be more careful—this is no longer just a personal hobby repo :-)

**Comment by mikaelsundell** [comment]
May I ask if the installation instructions are clear enough for someone who isn't very technical? Is there anything I can do to make the installation easier?

**Comment by atriantas** [comment]
Thank for finding a solution to my problem.
I think copying the files at the LUT folder is simple. I can say more when I will be able to use the DCTLs.
Also, you can give a unique name to the project, so people can talk about it.
It is a really interesting way for negative conversion but you have to search a lot to find it.
Maybe talking about it on LiftGammaGain or Youtube, to make the repo more active.

**Comment by mikaelsundell** [comment]
Thanks for the feedback.
I've made some changes to improve compatibility with CUDA on Windows. Please give it a try. Metal is very forgiving and C-styled, but CUDA is not.

**Comment by atriantas** [comment]
Unfortunatelly, I am still getting an error. 
I downloaded the files from the Code --> Download ZIP Button and the copy - paste the files at LUT folder.
The MS-Stripify and MS-Saturation were working before but not now.
I tried installing a previous version of DaVinci but I am still getting the same errors.
Do you think is something wrong with my setup? Do I have to use a specific Timeline Color Space?
Can I try something to make the debugging easier?

[0x0000400c] | DVIP                 | ERROR | 2024-11-05 21:46:16,286 | DaVinci CTL compilation failed.
[0x0000400c] | DVIP                 | ERROR | 2024-11-05 21:46:16,286 | Failed to build program.
Build Status: -2
Build Options:  -w -DDEVICE_IS_OPENCL -DCOMPILER_IS_DVIP_RT -DKERNEL_TYPE_IS_DCTL -DVENDOR_IS_NVIDIA -cl-mad-enable -cl-fast-relaxed-math
Build Log: <kernel>:1805:17: error: invalid conversion between vector type 'float3' and scalar type 'float'
    float3 ey = _fmaxf(y, eps);
                ^~~~~~~~~~~~~~
<kernel>:55:38: note: expanded from macro '_fmaxf'
    #define _fmaxf(_X, _Y)      fmax((float)(_X), (float)(_Y))
                                     ^~~~~~~~~~~
<kernel>:1989:14: error: must use 'struct' tag to refer to type 'CineonColor'
__CONSTANT__ CineonColor cineon_colors[] = {
             ^
             struct 

![DCTL_Folder_2](https://github.com/user-attachments/assets/36d8ade7-72bb-40c9-992d-eb22f83a88a1)

**Comment by mikaelsundell** [comment]
Give it another try; it should be fixed now—there was a small typo with float vs. float3 types.

**Comment by atriantas** [comment]
The MS-Saturation and MS-Stripify are now fixed but I still have the same problem with the MS-Cineon-Exposure, MS-Cineon-Invert, MS-Grade, MS-LogC3-Exposure, MS-LogC3-Print, MS-LogC3-Temperature. 
I am not sure about the transform DCTLs.

**Comment by mikaelsundell** [comment]
Got it, these are OpenCL errors. What type of GPU are you running?
I need to investigate this further, as it requires some additional changes. There are quite a few things supported in CUDA and Metal but not in OpenCL for some reason. Can you switch over to CUDA short term? The new code will be ready 1-2 days from now.

**Comment by atriantas** [comment]
Ok, I see. This is because I can only use OpenGL in DaVinci.
My GPU is CUDA 11 which is not supported. 
I can use CUDA only with Resolve versions below 16.2.6.
Thank you so much for your help!

**Comment by mikaelsundell** [comment]
No worries, I'll take care of it. I need to support OpenCL anyway; I just need a bit more time to think through the best way to properly restructure my structs and functions.

**Comment by atriantas** [comment]
Of course, take your time and have a good night!

**Comment by mikaelsundell** [comment]
I had to make a few adjustments to clean up the code and ensure support for Metal, CUDA, and OpenCL. I learned a lot in the process. I've tested the DCTLs on both Windows and Mac with OpenCL, and they should now be ready for a final test. Just a note: the sample negative still needs a bit of refinement, so try not to rely on it too heavily. I'll update the sample files later this week when I have some free time.

**Comment by atriantas** [comment]
All the DCTLs work now. 
The only thing is the three sliders "Density" "Bitdepth" and "Offset" that I don't see any change on the input or I don't know what they are doing.
Nevertheless, I am getting a nice inversion and I will play with some negatives when I have more free time on the weekend.
I will also try your way handling the raw image with rawtoaces tool because now I am using Rawtherapee and it's ICC profile creator with Linear profile created from the DNG of my camera.
Thank you!

**Comment by mikaelsundell** [comment]
It's fixed now, typo after changing the code structure to better support OpenCL. Send me an email on mikael.sundell at gmail.com if you are interested discussing rawtoaces and it's camera profiles.
